### ISSUE TITLE
Iterate trought existing project loaded

### ISSUE THREAD

**Issue by PetryJe** [scia-garage/SciaOpenAPI_example_VBA_simple_structure#5]
Hello everyone,

I am trying to iterate trought an existing project. What I need, is to list all existing beams, points, loads... inside this project in an Excel sheet. After that I want to have the possibility to change the size of the beams, the value of the load... inside the excel sheet and send the new value to SCIA.

But I am far from what I want to do because I don't know how I can get informations from the existing project. I have see that we have a command FindBeamDsId in the class Beam, but I got an error trying to use it:

``
Sub test()

Private Sub GetPointsFromSCIA_Click()
On Error GoTo bug

Dim TempFolder As String

Dim SENpath As String
SENpath = Sheets("Input").Cells(10, 2).Value

Dim templ As String
templ = "C:\Je\500c.esa"

Dim env As New SCIA_OpenAPI.Environment

'Setting of environment
Call env.Init(SENpath, "c:\tmp", "1.0.0.0")

'Start of SCIA Engineer
Dim openedSE As Boolean
Dim proj As EsaProject

Set proj = env.OpenProject(templ)

Dim Beams As SCIA_OpenAPI.Structure
Dim aa As Long
aa = Beams.FindBeamDsId("B8")  '<--- BUG here trying to get something with an element called "B8" which is existing inside the project loaded

Exit Sub

bug:
MsgBox "bug"

End Sub
``

This is probably not the good method, but actually without more exemple I am not able to do what I need to speedup my work. 

Hoping someone will help.

Thank you in advance !

**Comment by jarabroz** [comment]
Hello,

unfortunately, there is not any method of how you can get content of the existing project. The current implementation of OpenAPI is limited to create objects.  There is one workaround - you can open your project in SCIA Engineer and through Table Input functionality to export it to EXCEL. Then you can use the content of the project in EXCEL.
The method which you have used - FindBeamDsId is one of the internal methods which is accidentally set as public.
